import { ModelSpec } from '../types';
import { OLLAMA_CONFIG } from '../constants';

export const AVAILABLE_MODELS: ModelSpec[] = [
  {
    id: 'smollm2-135m',
    name: 'Tiny Brain',
    tagline: 'Instant Browser SLM',
    family: 'browser-slm',
    hfRepo: 'HuggingFaceTB/SmolLM2-135M-Instruct',
    sizeLabel: '~114 MB',
    approxParams: '135M',
    defaultDtype: 'q4f16',
    isSmallModel: true,
    description: 'SmolLM2 (0.135 B)',
    speedRating: 'Instant',
    isDefault: true,
    ramRequired: '< 250 MB',
  },
  {
    id: 'smollm2-360m',
    name: 'Small Brain',
    tagline: 'Balanced Fast SLM',
    family: 'browser-slm',
    hfRepo: 'HuggingFaceTB/SmolLM2-360M-Instruct',
    sizeLabel: '~190 MB',
    approxParams: '360M',
    defaultDtype: 'q4f16',
    isSmallModel: true,
    description: 'SmolLM2 (0.360 B)',
    speedRating: 'Ultra Fast',
    ramRequired: '~400 MB',
  },
  {
    id: 'qwen2.5-0.5b',
    name: 'Medium Brain',
    tagline: 'Intelligent Pocket SLM',
    family: 'browser-slm',
    hfRepo: 'onnx-community/Qwen2.5-0.5B-Instruct',
    sizeLabel: '~756 MB',
    approxParams: '0.5B',
    defaultDtype: 'q4',
    isSmallModel: false,
    description: 'Qwen 2.5 (0.500 B)',
    speedRating: 'Fast',
    ramRequired: '~600 MB',
  },
  {
    id: 'llama-3.2-1b',
    name: 'Meta Brain',
    tagline: 'Meta Compact SLM',
    family: 'browser-slm',
    hfRepo: 'onnx-community/Llama-3.2-1B-Instruct-ONNX',
    sizeLabel: '~720 MB',
    approxParams: '1B',
    defaultDtype: 'q4',
    isSmallModel: false,
    description: 'Llama 3.2 (1.000B)',
    speedRating: 'Balanced',
    ramRequired: '~1.2 GB',
  },
  {
    id: 'minicpm-2b',
    name: 'Big Brain',
    tagline: 'OpenBMB Deep Reasoning SLM',
    family: 'browser-slm',
    hfRepo: 'openbmb/MiniCPM5-2B',
    sizeLabel: '~1.3 GB',
    approxParams: '2B',
    defaultDtype: 'q4',
    isSmallModel: false,
    description: 'MiniCPM 5 (2.000 B)',
    speedRating: 'Deep',
    ramRequired: '~2.2 GB',
  },
  {
    id: 'muxai-ollama',
    name: 'MuxAI Brain',
    tagline: 'Cloud Ollama Server',
    family: 'ollama',
    hfRepo: 'ollama/muxai',
    sizeLabel: 'Cloud Server',
    approxParams: 'Full Power',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Llama 3.1 (8.000 B)',
    speedRating: 'Deep',
    endpointUrl: OLLAMA_CONFIG.muxAiEndpoint,
  },
  {
    id: 'self-hosted-ollama',
    name: 'Custom Brain',
    tagline: 'Custom Remote / Local Ollama',
    family: 'ollama',
    hfRepo: 'ollama/custom',
    sizeLabel: 'Custom URL',
    approxParams: 'Self-hosted',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Connect directly to your server',
    speedRating: 'Fast',
    isCustomOllama: true,
  },
];

export const DEFAULT_MODEL_ID = 'smollm2-135m';

export function getModelById(id: string): ModelSpec {
  return AVAILABLE_MODELS.find((m) => m.id === id) || AVAILABLE_MODELS[0];
}
