import { ModelSpec } from '../types';
import { OLLAMA_CONFIG } from '../constants';

export const AVAILABLE_MODELS: ModelSpec[] = [
  {
    id: 'smollm2-135m',
    name: 'Tiny Brain',
    tagline: 'Instant Browser SLM',
    family: 'browser-slm',
    hfRepo: 'HuggingFaceTB/SmolLM2-135M-Instruct',
    sizeLabel: '~114 MB',
    approxParams: '135M',
    defaultDtype: 'q4f16',
    isSmallModel: true,
    description: 'SmolLM2 (0.135 B)',
    speedRating: 'Instant',
    isDefault: true,
    ramRequired: '< 250 MB',
  },
  {
    id: 'smollm2-360m',
    name: 'Small Brain',
    tagline: 'Balanced Fast SLM',
    family: 'browser-slm',
    hfRepo: 'HuggingFaceTB/SmolLM2-360M-Instruct',
    sizeLabel: '~190 MB',
    approxParams: '360M',
    defaultDtype: 'q4f16',
    isSmallModel: true,
    description: 'SmolLM2 (0.360 B)',
    speedRating: 'Ultra Fast',
    ramRequired: '~400 MB',
  },
  {
    id: 'qwen2.5-0.5b',
    name: 'Medium Brain',
    tagline: 'Intelligent Pocket SLM',
    family: 'browser-slm',
    hfRepo: 'onnx-community/Qwen2.5-0.5B-Instruct',
    sizeLabel: '~756 MB',
    approxParams: '0.5B',
    defaultDtype: 'q4',
    isSmallModel: false,
    description: 'Qwen 2.5 (0.500 B)',
    speedRating: 'Fast',
    ramRequired: '~600 MB',
  },
  {
    id: 'llama-3.2-1b',
    name: 'Meta Brain',
    tagline: 'Meta Compact SLM',
    family: 'browser-slm',
    hfRepo: 'onnx-community/Llama-3.2-1B-Instruct-ONNX',
    sizeLabel: '~720 MB',
    approxParams: '1B',
    defaultDtype: 'q4',
    isSmallModel: false,
    description: 'Llama 3.2 (1.000B)',
    speedRating: 'Balanced',
    ramRequired: '~1.2 GB',
  },
  {
    id: 'minicpm-2b',
    name: 'Big Brain',
    tagline: 'OpenBMB Deep Reasoning SLM',
    family: 'browser-slm',
    hfRepo: 'openbmb/MiniCPM5-2B',
    sizeLabel: '~1.3 GB',
    approxParams: '2B',
    defaultDtype: 'q4',
    isSmallModel: false,
    description: 'MiniCPM 5 (2.000 B)',
    speedRating: 'Deep',
    ramRequired: '~2.2 GB',
  },
  {
    id: 'muxai-ollama',
    name: 'MuxAI Brain',
    tagline: 'Cloud Ollama Server',
    family: 'ollama',
    hfRepo: 'ollama/muxai',
    sizeLabel: 'Cloud Server',
    approxParams: 'Full Power',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Llama 3.1 (8.000 B)',
    speedRating: 'Deep',
    endpointUrl: OLLAMA_CONFIG.muxAiEndpoint,
  },
  {
    id: 'self-hosted-ollama',
    name: 'Custom Brain',
    tagline: 'Custom Remote / Local Ollama',
    family: 'ollama',
    hfRepo: 'ollama/custom',
    sizeLabel: 'Custom URL',
    approxParams: 'Self-hosted',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Connect directly to your server',
    speedRating: 'Fast',
    isCustomOllama: true,
  },
  // External AI Model APIs
  {
    id: 'openai-api',
    name: 'OpenAI API',
    tagline: 'GPT-4o, GPT-4o-mini & o3-mini',
    family: 'api-provider',
    providerId: 'openai',
    logoUrl: 'https://muxai.vercel.app/logos/openai.jpg',
    hfRepo: 'openai/gpt-4o',
    sizeLabel: 'Cloud API',
    approxParams: 'Flagship LLM',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: gpt-4o',
    speedRating: 'Ultra Fast',
    customModel: 'gpt-4o',
  },
  {
    id: 'gemini-api',
    name: 'Gemini API',
    tagline: 'Gemini 2.5 Flash & Pro',
    family: 'api-provider',
    providerId: 'gemini',
    logoUrl: 'https://muxai.vercel.app/logos/gemini.jpg',
    hfRepo: 'google/gemini-2.5-flash',
    sizeLabel: 'Cloud API',
    approxParams: 'Multimodal',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: gemini-2.5-flash',
    speedRating: 'Instant',
    customModel: 'gemini-2.5-flash',
  },
  {
    id: 'anthropic-api',
    name: 'Anthropic API',
    tagline: 'Claude 3.7 Sonnet & 3.5 Haiku',
    family: 'api-provider',
    providerId: 'anthropic',
    logoUrl: 'https://muxai.vercel.app/logos/claude.jpg',
    hfRepo: 'anthropic/claude-3-7-sonnet',
    sizeLabel: 'Cloud API',
    approxParams: 'Hybrid Reasoning',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: claude-3-7-sonnet-20250219',
    speedRating: 'Fast',
    customModel: 'claude-3-7-sonnet-20250219',
  },
  {
    id: 'xai-api',
    name: 'xAI API',
    tagline: 'Grok 2 & Grok Beta',
    family: 'api-provider',
    providerId: 'xai',
    logoUrl: 'https://muxai.vercel.app/logos/grok.jpg',
    hfRepo: 'xai/grok-2',
    sizeLabel: 'Cloud API',
    approxParams: 'Grok Intelligence',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: grok-2-1212',
    speedRating: 'Fast',
    customModel: 'grok-2-1212',
  },
  {
    id: 'groq-api',
    name: 'Groq API',
    tagline: 'Llama 3.3 70B on LPU speed',
    family: 'api-provider',
    providerId: 'groq',
    logoUrl: 'https://muxai.vercel.app/logos/groq.jpg',
    hfRepo: 'groq/llama-3.3-70b',
    sizeLabel: 'LPU Speed',
    approxParams: '70B Versatile',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: llama-3.3-70b-versatile',
    speedRating: 'Ultra Fast',
    customModel: 'llama-3.3-70b-versatile',
  },
  {
    id: 'zai-api',
    name: 'Z.ai API',
    tagline: 'GLM-4 Plus & GLM-4 Flash',
    family: 'api-provider',
    providerId: 'zai',
    logoUrl: 'https://muxai.vercel.app/logos/zai.jpg',
    hfRepo: 'zhipu/glm-4',
    sizeLabel: 'Cloud API',
    approxParams: 'Bilingual LLM',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: glm-4-plus',
    speedRating: 'Fast',
    customModel: 'glm-4-plus',
  },
  {
    id: 'deepseek-api',
    name: 'DeepSeek API',
    tagline: 'DeepSeek-V3 & DeepSeek-R1',
    family: 'api-provider',
    providerId: 'deepseek',
    logoUrl: 'https://muxai.vercel.app/logos/deepseek.jpg',
    hfRepo: 'deepseek/deepseek-chat',
    sizeLabel: 'Cloud API',
    approxParams: 'Deep Reasoning',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: deepseek-chat',
    speedRating: 'Fast',
    customModel: 'deepseek-chat',
  },
  {
    id: 'qwen-api',
    name: 'Qwen API',
    tagline: 'Alibaba Cloud Qwen-Max & Turbo',
    family: 'api-provider',
    providerId: 'qwen',
    logoUrl: 'https://muxai.vercel.app/logos/qwen.jpg',
    hfRepo: 'alibaba/qwen-max',
    sizeLabel: 'Cloud API',
    approxParams: 'Alibaba Cloud',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: qwen-max',
    speedRating: 'Fast',
    customModel: 'qwen-max',
  },
  {
    id: 'huggingface-api',
    name: 'HuggingFace API',
    tagline: 'Serverless Inference Router',
    family: 'api-provider',
    providerId: 'huggingface',
    logoUrl: 'https://muxai.vercel.app/logos/huggingface.jpg',
    hfRepo: 'meta-llama/Llama-3.3-70B-Instruct',
    sizeLabel: 'HF Hub',
    approxParams: 'Open Weights',
    defaultDtype: 'fp16',
    isSmallModel: false,
    description: 'Default: meta-llama/Llama-3.3-70B-Instruct',
    speedRating: 'Fast',
    customModel: 'meta-llama/Llama-3.3-70B-Instruct',
  },
];

export const DEFAULT_MODEL_ID = 'smollm2-135m';

export function getModelById(id: string): ModelSpec {
  return AVAILABLE_MODELS.find((m) => m.id === id) || AVAILABLE_MODELS[0];
}
